from openai import AsyncOpenAI

from config.settings import (
    OPENAI_API_KEY,
    OPENAI_MODEL,
    OPENAI_REASONING_EFFORT,
    AGENT_SYSTEM_PROMPT
)


client = AsyncOpenAI(
    api_key=OPENAI_API_KEY
)


async def ask_openai_stream(prompt: str):
    """Stream text generated by the OpenAI Responses API."""
    response = await client.responses.create(
        model=OPENAI_MODEL,
        instructions=AGENT_SYSTEM_PROMPT,
        input=prompt,
        reasoning={"effort": OPENAI_REASONING_EFFORT},
        stream=True,
    )

    async for chunk in response:
        if chunk.type == "response.output_text.delta":
            yield chunk.delta
